# Generated by Django 5.1 on 2024-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='technologies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
